version: '3.8'

services:
  web:
    build: .
    ports:
      - '5080:5080'
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
    command: ['redis-server', '--appendonly', 'yes']
